x-superset-env-file: &superset-env-file ./config/.env-superset
x-spark-env-file: &spark-env-file ./config/.env-spark
x-superset-image: &superset-image apachesuperset.docker.scarf.sh/apache/superset:${TAG:-latest-dev}
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes
  - ./docker:/app/docker
  - ./config/superset_config.py:/app/pythonpath/superset_config.py
  - superset_home:/app/superset_home

version: '3.7'
services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    env_file: *superset-env-file
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./superset_database:/var/lib/postgresql/data


  superset:
    env_file: *superset-env-file
    image: *superset-image
    container_name: superset_app
    command: ['/app/docker/docker-bootstrap.sh', 'app-gunicorn']
    user: 'root'
    restart: unless-stopped
    ports:
      - '8088:8088'
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ['/app/docker/docker-init.sh']
    env_file: *superset-env-file
    depends_on: *superset-depends-on
    user: 'root'
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ['/app/docker/docker-bootstrap.sh', 'worker']
    env_file: *superset-env-file
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: 'root'
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME',
        ]

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ['/app/docker/docker-bootstrap.sh', 'beat']
    env_file: *superset-env-file
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: 'root'
    volumes: *superset-volumes
    healthcheck:
      disable: true

  spark:
    image: docker.io/bitnami/spark:3.5
    env_file: *spark-env-file
    environment:
      - SPARK_MODE=master
    volumes:
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - '8080:8080'

  spark-worker-1:
    image: docker.io/bitnami/spark:3.5
    env_file: *spark-env-file
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=8081
      - GRANT_SUDO=yes
    user: root
    depends_on:
      - spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - '8081:8081'

  spark-worker-2:
    image: docker.io/bitnami/spark:3.5
    env_file: *spark-env-file
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=8082
      - GRANT_SUDO=yes
    user: root
    depends_on:
      - spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - '8082:8082'

  spark-worker-3:
    image: docker.io/bitnami/spark:3.5
    env_file: *spark-env-file
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=8083
      - GRANT_SUDO=yes
    user: root
    depends_on:
      - spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - '8083:8083'

  jupyter:
    image: 'jupyter/pyspark-notebook'
    env_file: *spark-env-file
    user: root
    environment:
      - GRANT_SUDO=yes
    command: >
      bash -c "pip install thrift thrift_sasl pyhive sqlalchemy
      && start-notebook.sh --NotebookApp.token='token'"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./config/spark-defaults.conf:/usr/local/spark/conf/spark-defaults.conf
    ports:
      - '127.0.0.1:8888:8888'
      - '4040:4040'
      - '10000:10000'

volumes:
  superset_home:
    external: false
  redis:
    external: false
